name: CI
on: push
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 11
      - name: install
        run: npm install
      - name: lint
        run: script/lint-ci
      - name: test
        run: npm test
      - name: prepublish
        run: script/prepublish
      - name: test deprecations
        if: startsWith(github.ref, 'refs/heads/release-')
        run: script/test-deprecations.js
